from .templates import (
    ORCHESTRATOR_PROMPT,
    MISSING_FILE_DETECTOR_PROMPT,
    DUPLICATED_FAILED_DETECTOR_PROMPT,
    EMPTY_FILE_DETECTOR_PROMPT,
    VOLUME_VARIATION_DETECTOR_PROMPT,
    LATE_UPLOAD_DETECTOR_PROMPT,
    PREVIOUS_PERIOD_DETECTOR_PROMPT,
    REPORT_CONSOLIDATOR_PROMPT,
)
